require 'rails_helper'

RSpec.describe ShippingRate do


context "we get a response with rates" do
  hash = {:created_at=>"2018-02-16T04:40:13Z",
         :is_return=>false,
         :messages=>[],
         :mode=>"test",
         :options=>{:currency=>"USD", :payment=>{:type=>"SENDER"}, :label_date=>nil, :date_advance=>0},
         :reference=>nil,
         :status=>"unknown",
         :tracking_code=>nil,
         :updated_at=>"2018-02-16T04:40:13Z",
         :batch_id=>nil,
         :batch_status=>nil,
         :batch_message=>nil,
         :customs_info=>nil,
         :from_address=>
          {:id=>"adr_7d6e9ab3b74e40d886cbd28fad3a277b",
           :object=>"Address",
           :created_at=>"2018-02-16T04:40:13Z",
           :updated_at=>"2018-02-16T04:40:13Z",
           :name=>nil,
           :company=>"Little Shop",
           :street1=>"1331 17th Street",
           :street2=>"L100",
           :city=>"Denver",
           :state=>"CO",
           :zip=>"80202",
           :country=>"US",
           :phone=>"3038765309",
           :email=>"blbillington1@gmail.com",
           :mode=>"test",
           :carrier_facility=>nil,
           :residential=>nil,
           :federal_tax_id=>nil,
           :state_tax_id=>nil,
           :verifications=>{}},
         :insurance=>nil,
         :order_id=>nil,
         :parcel=>
          {:id=>"prcl_464d20496ad44ba2b4e93d285ac75efe",
           :object=>"Parcel",
           :created_at=>"2018-02-16T04:40:13Z",
           :updated_at=>"2018-02-16T04:40:13Z",
           :length=>9.0,
           :width=>7.0,
           :height=>1.0,
           :predefined_package=>nil,
           :weight=>1.0,
           :mode=>"test"},
         :postage_label=>nil,
         :rates=>
          [{:id=>"rate_b268b2d6294640a0b0d0249b2893558b",
            :object=>"Rate",
            :created_at=>"2018-02-16T04:40:13Z",
            :updated_at=>"2018-02-16T04:40:13Z",
            :mode=>"test",
            :service=>"First",
            :carrier=>"USPS",
            :rate=>"2.66",
            :currency=>"USD",
            :retail_rate=>"3.50",
            :retail_currency=>"USD",
            :list_rate=>"2.66",
            :list_currency=>"USD",
            :delivery_days=>3,
            :delivery_date=>nil,
            :delivery_date_guaranteed=>false,
            :est_delivery_days=>3,
            :shipment_id=>"shp_d3c225109adf4e8086a2188bb512c1ed",
            :carrier_account_id=>"ca_995df380aa994762a4363f8d961d742f"},
           {:id=>"rate_0e4e32e20ea64a74a785a08d0b474a2a",
            :object=>"Rate",
            :created_at=>"2018-02-16T04:40:13Z",
            :updated_at=>"2018-02-16T04:40:13Z",
            :mode=>"test",
            :service=>"ParcelSelect",
            :carrier=>"USPS",
            :rate=>"7.19",
            :currency=>"USD",
            :retail_rate=>"7.19",
            :retail_currency=>"USD",
            :list_rate=>"7.19",
            :list_currency=>"USD",
            :delivery_days=>6,
            :delivery_date=>nil,
            :delivery_date_guaranteed=>false,
            :est_delivery_days=>6,
            :shipment_id=>"shp_d3c225109adf4e8086a2188bb512c1ed",
            :carrier_account_id=>"ca_995df380aa994762a4363f8d961d742f"},
           {:id=>"rate_31317c5d0a5847158eb87f32ecd8c099",
            :object=>"Rate",
            :created_at=>"2018-02-16T04:40:13Z",
            :updated_at=>"2018-02-16T04:40:13Z",
            :mode=>"test",
            :service=>"Express",
            :carrier=>"USPS",
            :rate=>"24.66",
            :currency=>"USD",
            :retail_rate=>"27.70",
            :retail_currency=>"USD",
            :list_rate=>"24.66",
            :list_currency=>"USD",
            :delivery_days=>nil,
            :delivery_date=>nil,
            :delivery_date_guaranteed=>false,
            :est_delivery_days=>nil,
            :shipment_id=>"shp_d3c225109adf4e8086a2188bb512c1ed",
            :carrier_account_id=>"ca_995df380aa994762a4363f8d961d742f"},
           {:id=>"rate_e7a8d6b60cc24bed9e8b5b28383c524d",
            :object=>"Rate",
            :created_at=>"2018-02-16T04:40:13Z",
            :updated_at=>"2018-02-16T04:40:13Z",
            :mode=>"test",
            :service=>"Priority",
            :carrier=>"USPS",
            :rate=>"6.98",
            :currency=>"USD",
            :retail_rate=>"7.45",
            :retail_currency=>"USD",
            :list_rate=>"7.20",
            :list_currency=>"USD",
            :delivery_days=>2,
            :delivery_date=>nil,
            :delivery_date_guaranteed=>false,
            :est_delivery_days=>2,
            :shipment_id=>"shp_d3c225109adf4e8086a2188bb512c1ed",
            :carrier_account_id=>"ca_995df380aa994762a4363f8d961d742f"}],
         :refund_status=>nil,
         :scan_form=>nil,
         :selected_rate=>nil,
         :tracker=>nil,
         :to_address=>
          {:id=>"adr_511fd7bf7089458a802dcb246f671d99",
           :object=>"Address",
           :created_at=>"2018-02-16T04:40:13Z",
           :updated_at=>"2018-02-16T04:40:13Z",
           :name=>"Lauren Billington",
           :company=>nil,
           :street1=>"2642 E 10th Street",
           :street2=>"",
           :city=>"Bloomington",
           :state=>"IN",
           :zip=>"47408",
           :country=>"US",
           :phone=>"",
           :email=>nil,
           :mode=>"test",
           :carrier_facility=>nil,
           :residential=>nil,
           :federal_tax_id=>nil,
           :state_tax_id=>nil,
           :verifications=>{}},
         :usps_zone=>5,
         :return_address=>
          {:id=>"adr_7d6e9ab3b74e40d886cbd28fad3a277b",
           :object=>"Address",
           :created_at=>"2018-02-16T04:40:13Z",
           :updated_at=>"2018-02-16T04:40:13Z",
           :name=>nil,
           :company=>"Little Shop",
           :street1=>"1331 17th Street",
           :street2=>"L100",
           :city=>"Denver",
           :state=>"CO",
           :zip=>"80202",
           :country=>"US",
           :phone=>"3038765309",
           :email=>"blbillington1@gmail.com",
           :mode=>"test",
           :carrier_facility=>nil,
           :residential=>nil,
           :federal_tax_id=>nil,
           :state_tax_id=>nil,
           :verifications=>{}},
         :buyer_address=>
          {:id=>"adr_511fd7bf7089458a802dcb246f671d99",
           :object=>"Address",
           :created_at=>"2018-02-16T04:40:13Z",
           :updated_at=>"2018-02-16T04:40:13Z",
           :name=>"Lauren Billington",
           :company=>nil,
           :street1=>"2642 E 10th Street",
           :street2=>"",
           :city=>"Bloomington",
           :state=>"IN",
           :zip=>"47408",
           :country=>"US",
           :phone=>"",
           :email=>nil,
           :mode=>"test",
           :carrier_facility=>nil,
           :residential=>nil,
           :federal_tax_id=>nil,
           :state_tax_id=>nil,
           :verifications=>{}},
         :forms=>[],
         :fees=>[],
         :id=>"shp_d3c225109adf4e8086a2188bb512c1ed",
         :object=>"Shipment"}

    subject {ShippingRate.new(hash)}

    describe "#retail_rate_first" do
      it "returns the retails rate from the API response" do
        expect(subject.retail_rate_priority).to eq("7.45")
      end
    end
  end




  context "we get a response without rates" do
    hash = {:created_at=>"2018-02-16T04:55:07Z",
         :is_return=>false,
         :messages=>
          [{:type=>"rate_error",
            :carrier=>"USPS",
            :message=>"Unable to retrieve USPS rates without a valid destination zip code."}],
         :mode=>"test",
         :options=>{:currency=>"USD", :payment=>{:type=>"SENDER"}, :label_date=>nil, :date_advance=>0},
         :reference=>nil,
         :status=>"unknown",
         :tracking_code=>nil,
         :updated_at=>"2018-02-16T04:55:07Z",
         :batch_id=>nil,
         :batch_status=>nil,
         :batch_message=>nil,
         :customs_info=>nil,
         :from_address=>
          {:id=>"adr_20bbc7574e4c4b9387d676a8bba55bf1",
           :object=>"Address",
           :created_at=>"2018-02-16T04:55:07Z",
           :updated_at=>"2018-02-16T04:55:07Z",
           :name=>nil,
           :company=>"Little Shop",
           :street1=>"1331 17th Street",
           :street2=>"L100",
           :city=>"Denver",
           :state=>"CO",
           :zip=>"80202",
           :country=>"US",
           :phone=>"3038765309",
           :email=>"blbillington1@gmail.com",
           :mode=>"test",
           :carrier_facility=>nil,
           :residential=>nil,
           :federal_tax_id=>nil,
           :state_tax_id=>nil,
           :verifications=>{}},
         :insurance=>nil,
         :order_id=>nil,
         :parcel=>
          {:id=>"prcl_d39a5909d1d34551bc18fa8b898cecb8",
           :object=>"Parcel",
           :created_at=>"2018-02-16T04:55:07Z",
           :updated_at=>"2018-02-16T04:55:07Z",
           :length=>9.0,
           :width=>7.0,
           :height=>1.0,
           :predefined_package=>nil,
           :weight=>1.0,
           :mode=>"test"},
         :postage_label=>nil,
         :rates=>[],
         :refund_status=>nil,
         :scan_form=>nil,
         :selected_rate=>nil,
         :tracker=>nil,
         :to_address=>
          {:id=>"adr_121aa91c20cd474baef761f62ef3ed5c",
           :object=>"Address",
           :created_at=>"2018-02-16T04:55:07Z",
           :updated_at=>"2018-02-16T04:55:07Z",
           :name=>"Lauren Billington",
           :company=>nil,
           :street1=>"2642 E 10th Street",
           :street2=>"",
           :city=>"Bloomington",
           :state=>"IN",
           :zip=>"4321",
           :country=>"US",
           :phone=>"",
           :email=>nil,
           :mode=>"test",
           :carrier_facility=>nil,
           :residential=>nil,
           :federal_tax_id=>nil,
           :state_tax_id=>nil,
           :verifications=>{}},
         :usps_zone=>6,
         :return_address=>
          {:id=>"adr_20bbc7574e4c4b9387d676a8bba55bf1",
           :object=>"Address",
           :created_at=>"2018-02-16T04:55:07Z",
           :updated_at=>"2018-02-16T04:55:07Z",
           :name=>nil,
           :company=>"Little Shop",
           :street1=>"1331 17th Street",
           :street2=>"L100",
           :city=>"Denver",
           :state=>"CO",
           :zip=>"80202",
           :country=>"US",
           :phone=>"3038765309",
           :email=>"blbillington1@gmail.com",
           :mode=>"test",
           :carrier_facility=>nil,
           :residential=>nil,
           :federal_tax_id=>nil,
           :state_tax_id=>nil,
           :verifications=>{}},
         :buyer_address=>
          {:id=>"adr_121aa91c20cd474baef761f62ef3ed5c",
           :object=>"Address",
           :created_at=>"2018-02-16T04:55:07Z",
           :updated_at=>"2018-02-16T04:55:07Z",
           :name=>"Lauren Billington",
           :company=>nil,
           :street1=>"2642 E 10th Street",
           :street2=>"",
           :city=>"Bloomington",
           :state=>"IN",
           :zip=>"4321",
           :country=>"US",
           :phone=>"",
           :email=>nil,
           :mode=>"test",
           :carrier_facility=>nil,
           :residential=>nil,
           :federal_tax_id=>nil,
           :state_tax_id=>nil,
           :verifications=>{}},
         :forms=>[],
         :fees=>[],
         :id=>"shp_3d70eb3c197c430ba22af184cd9f68dc",
         :object=>"Shipment"}

    subject {ShippingRate.new(hash)}

      describe "message" do
        it "returns a message about a failed API call" do
          expect(subject.message).to eq("Unable to retrieve USPS rates without a valid destination zip code.")
      end
    end
  end


end
